### ISSUE TITLE
subtract wide field

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#119]
For this we simply need to copy the first part of this https://github.com/mhardcastle/ddf-pipeline/blob/SubSquare/pipeline.py into the new pipeline.

**Comment by mhardcastle** [comment]
Yeah, but we should image a wider field. And let's make the whole thing configurable...
-------- Original message --------From: twshimwell <notifications@github.com> Date: 01/11/2018  13:24  (GMT+01:00) To: mhardcastle/ddf-pipeline <ddf-pipeline@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [mhardcastle/ddf-pipeline] subtract wide field (#119) 
For this we simply need to copy the first part of this https://github.com/mhardcastle/ddf-pipeline/blob/SubSquare/pipeline.py into the new pipeline.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhardcastle/ddf-pipeline","title":"mhardcastle/ddf-pipeline","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhardcastle/ddf-pipeline"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"subtract wide field (#119)"}],"action":{"name":"View Issue","url":"https://github.com/mhardcastle/ddf-pipeline/issues/119"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhardcastle/ddf-pipeline/issues/119",
"url": "https://github.com/mhardcastle/ddf-pipeline/issues/119",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "subtract wide field (#119)",
"sections": [
{
"text": "",
"activityTitle": "**twshimwell**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@twshimwell",
"facts": [
{
"name": "Repository: ",
"value": "mhardcastle/ddf-pipeline"
},
{
"name": "Issue #: ",
"value": 119
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 119,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 119\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mhardcastle/ddf-pipeline/issues/119"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 404305949\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mhardcastle** [comment]
Merged Wendy's code. I guess I'll close this and we should open new issues if there are problems or enhancements.

**Comment by twshimwell** [comment]
Did you have any comparison images between doing this and not doing it Wendy? Or was it more just a necessity to deal with sources outside the field of view?
