### ISSUE TITLE
Error in DDF-image_full_ampphase_di

### ISSUE THREAD

**Issue by AnnalisaB** [mhardcastle/ddf-pipeline#126]
Hi!

I'm runnind DDF on a Cycle1 observation. After several days of smooth processing I got the error I paste below.
I looked up in the first log and it seems there's nothing wrong after 11m4.4s of processing. 

Many thanks in advance

Annalisa

AsyncProcessPool          | [TB] [1.2/1.2 1.7/1.7 93.1Gb] worker 'comp16' killed by signal SIGKILL
AsyncProcessPool          | [TB] [1.2/1.2 1.7/1.7 93.1Gb] 1 worker(s) have died. Initiating shutdown.
- DDFacet                   | [1.2/4.0 1.9/4.9 93.1Gb] A worker process has died on us unexpectedly. This probably indicates a bug:
DDFacet                   | [1.2/4.0 1.9/4.9 93.1Gb]   the original underlying error may be reported in the log [possibly far] above.
- DDFacet                   | [1.2/4.0 1.9/4.9 93.1Gb] 
- DDFacet                   | [1.2/4.0 1.9/4.9 93.1Gb] There was a problem after 11m4.4s; if you think this is a bug please open an issue, 
2018-11-12 09:40:53:  - 09:40:53 - DDFacet                   | [1.2/4.0 1.9/4.9 93.1Gb]   quote your version of DDFacet and attach your logfile.
2018-11-12 09:40:53:  - 09:40:53 - DDFacet                   | [1.2/4.0 1.9/4.9 93.1Gb] You are using DDFacet revision: dev-cc860cf

**Comment by mhardcastle** [comment]
I'd guess this is a memory error. How much memory does your node have, and how many cores are you using? Can you see the system logs? -- if so, check if the 'out of memory killer' has run. Make sure all the memory is empty when DDFacet is not running.

**Comment by AnnalisaB** [comment]
Hi Martin, thanks for the rapid answer.
The node has 512GB RAM  and 20(+20) CPUs, 2 cores. Other runs of DDF have gone through in the past weeks/months
I'll see if I can access the system logs, but I wanted to ask what do you mean with "all the memory is empty when DDF is not running"? you mean no other jobs should be running even if they require little memory and 1 cpu?

**Comment by cyriltasse** [comment]
The shared RAM is important, can you chack that it's set to be able to use 100% of the RAM? Sometimes it's not, see

https://github.com/cyriltasse/DDFacet#userstroubleshooting-configure-max-shared-memory

**Comment by AnnalisaB** [comment]
Thanks, Cyril
I can't access the link, unfortunately

**Comment by cyriltasse** [comment]
Sorry - I've invited you

**Comment by AnnalisaB** [comment]
Thanks Cycil, I don't have root permission, I'll wait for the IT guy to arrive and let you know

**Comment by cyriltasse** [comment]
@mhardcastle I remember you had found something interesting on _hugepages_ or something? I don't see anything on the `README`...

**Comment by mhardcastle** [comment]
It's in `docs/manual.md`. But the hugepages thing, while it's important for efficiency, won't kill the process.

I think Annalisa's error message looks more like the OOM killer (the SIGKILL is the clue). Running out of space on /dev/shm directly generally gives other errors.

**Comment by mhardcastle** [comment]
It's in `docs/manual.md`. But the hugepages thing, while it's important for efficiency, won't kill the process.

I think Annalisa's error message looks more like the OOM killer (the SIGKILL is the clue). Running out of space on /dev/shm directly generally gives other errors.

**Comment by cyriltasse** [comment]
ye - `shm` issues gives more generally SIGBUS, right?

**Comment by mhardcastle** [comment]
Right.
-------- Original message --------From: cyriltasse <notifications@github.com> Date: 13/11/2018  12:29  (GMT+01:00) To: mhardcastle/ddf-pipeline <ddf-pipeline@noreply.github.com> Cc: Martin Hardcastle <mjh@extragalactic.info>, Mention <mention@noreply.github.com> Subject: Re: [mhardcastle/ddf-pipeline] Error in DDF-image_full_ampphase_di
  (#126) ye - shm issues gives more generally SIGBUS, right?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhardcastle/ddf-pipeline","title":"mhardcastle/ddf-pipeline","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhardcastle/ddf-pipeline"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cyriltasse in #126: ye - `shm` issues gives more generally SIGBUS, right?"}],"action":{"name":"View Issue","url":"https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438233506"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438233506",
"url": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438233506",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mhardcastle/ddf-pipeline] Error in DDF-image_full_ampphase_di (#126)",
"sections": [
{
"text": "",
"activityTitle": "**cyriltasse**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@cyriltasse",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 126,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 126\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438233506"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409483201\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by AnnalisaB** [comment]
I checked the sys log. 
shared memory in tmpfs has access to 256GB of RAM, that should be enough (?)

I forgot to specify the error happens when it finalizes weight before launching the
image_full_ampphase_di.parset
 
I inspected the log more carefully with Etienne and tried to relaunch the parset image_full_ampphase_di.parset but with NChunk-Hours=2 and it goes through. So it's definitely a memory problem here. Other people ran DDF on LOTSS fields on the same machine with no problem, but this dataset has a larger bandwidth than LOTSS pointing.
Is it possible to specify in the parset the NChunk-Hours parameter?

What is confusing me, though,  is that  it is not the first image that DDF made, and I checked the image size is the same as the first image, so why is it a problem only at this time after more than 1 week  of processing? Just curious...

Thanks

**Comment by mhardcastle** [comment]
So the error occurs the first time that the whole bandwidth is considered. Do you also have a shorter integration time or more channels per sub-band than a standard  LoTSS pointing?
-------- Original message --------From: AnnalisaB <notifications@github.com> Date: 13/11/2018  16:22  (GMT+01:00) To: mhardcastle/ddf-pipeline <ddf-pipeline@noreply.github.com> Cc: Martin Hardcastle <mjh@extragalactic.info>, Mention <mention@noreply.github.com> Subject: Re: [mhardcastle/ddf-pipeline] Error in DDF-image_full_ampphase_di
  (#126) I checked the sys log.
shared memory in tmpfs has access to 256GB of RAM, that should be enough (?)
I forgot to specify the error happens when it finalizes weight before launching the
image_full_ampphase_di.parset
I inspected the log more carefully with Etienne and tried to relaunch the parset image_full_ampphase_di.parset but with NChunk-Hours=2 and it goes through. So it's definitely a memory problem here. Other people ran DDF on LOTSS fields on the same machine with no problem, but this dataset has a larger bandwidth than LOTSS pointing.
Is it possible to specify in the parset the NChunk-Hours parameter?
What is confusing me, though,  is that  it is not the first image that DDF made, and I checked the image size is the same as the first image, so why is it a problem only at this time after more than 1 week  of processing? Just curious...
Thanks

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhardcastle/ddf-pipeline","title":"mhardcastle/ddf-pipeline","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhardcastle/ddf-pipeline"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AnnalisaB in #126: I checked the sys log. \r\nshared memory in tmpfs has access to 256GB of RAM, that should be enough (?)\r\n\r\nI forgot to specify the error happens when it finalizes weight before launching the\r\nimage_full_ampphase_di.parset\r\n \r\nI inspected the log more carefully with Etienne and tried to relaunch the parset image_full_ampphase_di.parset but with NChunk-Hours=2 and it goes through. So it's definitely a memory problem here. Other people ran DDF on LOTSS fields on the same machine with no problem, but this dataset has a larger bandwidth than LOTSS pointing.\r\nIs it possible to specify in the parset the NChunk-Hours parameter?\r\n\r\nWhat is confusing me, though,  is that  it is not the first image that DDF made, and I checked the image size is the same as the first image, so why is it a problem only at this time after more than 1 week  of processing? Just curious...\r\n\r\nThanks\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438304492"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438304492",
"url": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438304492",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mhardcastle/ddf-pipeline] Error in DDF-image_full_ampphase_di (#126)",
"sections": [
{
"text": "",
"activityTitle": "**AnnalisaB**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@AnnalisaB",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 126,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 126\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438304492"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409483201\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by AnnalisaB** [comment]
I have 40ch/SB and 4s time resolutions. The observation is 10h long, though, and it has more band
(from 111 to 170 MHz)
So I have in total 31 SB, 10h long

**Comment by mhardcastle** [comment]
Ok, normally we use 2 ch/sb and 8s (ie 20 channels per ms). So your data are likely a factor around 6 larger than we are expecting, and your machine is only a factor 2 larger than the ones we use...
-------- Original message --------From: AnnalisaB <notifications@github.com> Date: 13/11/2018  17:29  (GMT+01:00) To: mhardcastle/ddf-pipeline <ddf-pipeline@noreply.github.com> Cc: Martin Hardcastle <mjh@extragalactic.info>, Mention <mention@noreply.github.com> Subject: Re: [mhardcastle/ddf-pipeline] Error in DDF-image_full_ampphase_di
  (#126) I have 40ch/SB and 4s time resolutions. The observation is 10h long, though, and it has more band
(from 111 to 170 MHz)
So I have in total 31 SB, 10h long

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhardcastle/ddf-pipeline","title":"mhardcastle/ddf-pipeline","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhardcastle/ddf-pipeline"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AnnalisaB in #126:  I have 40ch/SB and 4s time resolutions. The observation is 10h long, though, and it has more band\r\n(from 111 to 170 MHz)\r\nSo I have in total 31 SB, 10h long\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438337255"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438337255",
"url": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438337255",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mhardcastle/ddf-pipeline] Error in DDF-image_full_ampphase_di (#126)",
"sections": [
{
"text": "",
"activityTitle": "**AnnalisaB**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@AnnalisaB",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 126,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 126\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438337255"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409483201\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by AnnalisaB** [comment]
mmm it all makes sense then
If it is not possible to specify NChunk-Hours in the parset
I will average the ms and restart the run. 

Many thanks

**Comment by mhardcastle** [comment]
Well, you will also get a significant speedup by averaging. If you like I can put the chunk-hours option into ddf-pipeline, though, it's easy...
-------- Original message --------From: AnnalisaB <notifications@github.com> Date: 13/11/2018  17:50  (GMT+01:00) To: mhardcastle/ddf-pipeline <ddf-pipeline@noreply.github.com> Cc: Martin Hardcastle <mjh@extragalactic.info>, Mention <mention@noreply.github.com> Subject: Re: [mhardcastle/ddf-pipeline] Error in DDF-image_full_ampphase_di
  (#126) mmm it all makes sense then
If it is not possible to specify NChunk-Hours in the parset
I will average the ms and restart the run.
Many thanks

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhardcastle/ddf-pipeline","title":"mhardcastle/ddf-pipeline","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhardcastle/ddf-pipeline"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AnnalisaB in #126: mmm it all makes sense then\r\nIf it is not possible to specify NChunk-Hours in the parset\r\nI will average the ms and restart the run. \r\n\r\nMany thanks"}],"action":{"name":"View Issue","url":"https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438345472"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438345472",
"url": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438345472",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mhardcastle/ddf-pipeline] Error in DDF-image_full_ampphase_di (#126)",
"sections": [
{
"text": "",
"activityTitle": "**AnnalisaB**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@AnnalisaB",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 126,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 126\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mhardcastle/ddf-pipeline/issues/126#issuecomment-438345472"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409483201\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mhardcastle** [comment]
@cyriltasse apparently that's what happens when I reply using e-mail on my phone. I'll try to remember not to do that....

**Comment by mhardcastle** [comment]
Closing the issue since no change to the code is requested.
