### ISSUE TITLE
QU cubes broken in master

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/ddf-pipeline#184]
When I merged Tim's massive_if branch it pulled in commit bb5d5b6bd09370b5169b52161b003e3355b266a6 which must have been made there. This causes the code to look for filenames `%s_QU_Cube*.cube.SmoothNorm.fits` instead of dirty.corr.fits. But these don't seem to be produced by DDFacet (branch `ddf_pipeline_fixes_may18`). @twshimwell do you know what's going on here? Were you using a different DDF version or what?

(this also means we have not been making the smooth beam corrections in the uploaded QU cubes, presumably. Oh well.)

**Comment by twshimwell** [comment]
Hmmm. Looking back at the tickets and trying to remember around the time of these changes ( https://github.com/mhardcastle/ddf-pipeline/issues/132) I think id modified pipeline.py in massive_if to keep these files but then the following day Cyril fixed the bug that made .corr.fits ones correct in DDFacet and in massive_if I hadnt changed it back. I think its been correct in master though since the DDFacet fix where we had continued to upload .corr files instead of smoothbeam (not sure what commit but this issue references it https://github.com/mhardcastle/ddf-pipeline/issues/137)

**Comment by twshimwell** [comment]
So yes SmoothNorm is wrong and it should be

cubefiles=['image_full_low_QU.cube.dirty.fits','image_full_low_QU.cube.dirty.corr.fits']

I thought

**Comment by mhardcastle** [comment]
Ah fair enough. So I should just revert the most recent commit to this file only. I wonder if I can make git do that...
