### ISSUE TITLE
blank_mosaic

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#185]
blank_mosaic in mosaic_pointing currently blanks the outskirts of a mosaiced map based on the maximum separation between the mosaics in the pointing. 

Isnt it nicer to use the beamcut value? So the central mosaic pointing weight map which is cut at the beamcut to do the blanking?

**Comment by twshimwell** [comment]
I noticed this as currently if you e.g. cut at pb=0.7 you get weird blanking -- left is the blanked mosaic and right is the mosaiced weight map. 

![Screenshot 2019-07-03 16 36 04](https://user-images.githubusercontent.com/12065270/60600619-c7004780-9db0-11e9-8add-c5c178b9d7ed.png)

**Comment by mhardcastle** [comment]
Well, I think the idea here that all the mosaics should be the same size because we have the same tiling strategy everywhere. It assumes that the blanking level is such that you can do this using maxsize, but we always want to do that, don't we?

**Comment by twshimwell** [comment]
Yeh normally we do. I think... what about at low declination though? Wont we chop within the 0.3pb point by looking at the distance of the max separation?

The reason im doing 0.7 and making these small mosaics is for the fluxscale corrections -- so making use of the mosaicing script for the projections and masking. This is because for determining the overlapping pixels between mosaics I just want those within say 0.7pb rather than say 0.3pb. I could just make the mosaics with 0.3pb and then do the cutting up afterwards myself but with the products that are stored from the mosaicing script its a bit fiddly to do this. Having the weird mosaics like i posted doesnt really make much difference for my purpose. I just thought they were a bit weird and wondered if we were doing the right thing.

**Comment by mhardcastle** [comment]
Yeah, but the tiling strategy is the same at low dec. The fundamental issue is that the mosaicing code only makes an image which is of order the tiling size. And that's kind of unfixable without putting in a manual factor, because the beam at low dec will be bigger than the region in which we make the weight images in the first place. Maybe we need that manual factor though.

For your purposes you could just put in an option to over-ride the maxsep code and fix the size in degrees of the output image?

(I notice that if you go to pb=0.7 you only get 4 overlaps instead of 6.)
