### ISSUE TITLE
Perhaps using wrong data column when do_wide=True

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#261]
When do_wide=True (for the wide  field source subtraction) we set colname="DATA_SUB" whilst o['colname'] =  DATA (or CORRECTED_DATA) generally. Also we soon after set column = 'DATA_DI_CORRECTED' (which is derived from DATA_SUB)

However, in the bootstrap step this we do:

                    d=t.getcol(o['colname'])
                    d*=factor
                    t.putcol('SCALED_DATA',d)

and also it will create "DATA_DI_CORRECTED_SCALED" (which is related to DATA_SUB) through:

                        newname=colname+'_SCALED'
                        desc['name']=newname
                        t.addcols(desc)
                        d=t.getcol(colname)
                        d*=factor
                        t.putcol(newname,d)

However, later in the pipeline prior to the DI steps we do:

            separator("Another DI step")
            if o['bootstrap']:
                colname='SCALED_DATA'
            else:
                colname=o['colname']

which will  then ignore that the colname was set to "DATA_SUB" 

Not sure what the simplest thing is but maybe after the subtraction if we set:

colname="DATA_SUB"
o['colname'] = 'DATA_SUB'

this'd do the trick.

**Comment by mhardcastle** [comment]
I don't think we want to change o['colname'] -- that should stay as being the user-defined option -- but we obviously should be scaling the right column. Isn't the correct thing to do to make the bootstrap code scale DATA_SUB if subtract is on? So that SCALED_DATA ends up with subtracted, scaled data?

I am a bit confused now how the subtraction and the bootstrap have ever worked together?

**Comment by twshimwell** [comment]
haha I dont know if they have... 

Yeh that would work if we do it like that within bootstrap.py

**Comment by mhardcastle** [comment]
It's interesting because we've been doing the subtraction for everything at low dec in current processing and we've certainly convinced ourselves that it's helping the imaging... but it doesn't seem as though the code will actually have done anything. We could try imaging the final uv data at low resolution to see whether it's actually been subtracted I suppose.

I'll have a look at fixing up the bootstrap code anyway.

**Comment by twshimwell** [comment]
Yeh I actually noticed it because id left the low resolution parameters to still make a large image and the sources were very much still there. I went back and made wide field images of the  various columns. DATA_SUB and DATA_DI_CORRECTED_SCALED indeed had the sources subtracted but not DATA_DI_CORRECTED which is the one used for the full bandwidth imaging.

**Comment by twshimwell** [comment]
fixed
