### ISSUE TITLE
Understand source sizes in DR2

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#71]
12arcsec seems too large and makes masks excessively large slowing things down. Looking at the logs DDFacet fits the psf to be 14x4arcsec which seems incorrect too...  Not quite sure what the best answer is. Fitting in casa gives 6x3 which also seems small.

Maybe we should instead use ~7arcsec though?

Also for the high resolution, maybe 6arcsec is similarly too high.

**Comment by twshimwell** [comment]
<img width="1076" alt="screenshot 2018-06-19 16 07 25" src="https://user-images.githubusercontent.com/12065270/41602458-20d732ec-73db-11e8-822f-0e027987101a.png">

**Comment by mhardcastle** [comment]
The 12 arcsec thing is basically there in order to keep the masks large and so help with extended structure. Before we change it (which is easy, it's just a default parameter and can be changed in a config file) we should check whether the effects are good or bad.

I think 6 arcsec is fine for HETDEX (we have to have a circular beam for mosaicing and that is a reasonable compromise which I checked with wsclean beam fitting some time ago). Will be different for different fields of course.

**Comment by mhardcastle** [comment]
PS the intermediate and final images _should_ have different resolutions because of the different robustnesses used (image_robust vs final_robust in the options). This is confused by the fact that the first all-ms image in the current pipeline uses final_robust but still uses the low-res restoring beam. Arguably that's wrong and we should either change the robustness or the restoring beam (at 'Deconvolution AP (full mslist)').

**Comment by twshimwell** [comment]
Ah yes, I have pushed a change so that this step now uses final_psf as it should (looking at the source sizes of these images all the deconvolved sources had 12" size and all the undeconvolved ones were 6" so it was a bit odd). The push I have done doesnt use final_psf_major or minor which are still only used on the final imaging step if they are specified.

**Comment by twshimwell** [comment]
I wonder if that bug in the image_full_ampphase_di_m imaging would have had any impact on the source sizes that are recovered in the final imaging step because its the mask from that step that is used for the final imaging.

**Comment by mhardcastle** [comment]
Possible I guess -- will be interesting to see if it makes a difference.

I think we should use the final_psf_major etc in this step consistently with what we do for the final imaging. If someone specifies those in the config file then it's because they think that is the correct psf for final_robust...

**Comment by twshimwell** [comment]
im testing but will be a little while to get IMAGING_WEIGHTS right and to redo the solutions with the newly masked dicomodel.

In the meantime ive updated the image_full_ampphase_di and image_full_ampphase_di_m to use the proper final_psf (so major, minor and angle)

**Comment by twshimwell** [comment]
Yes it always seems a bit of a long shot. To investigate this further im doing a run with no smoothing and also a run using 6arcsec and robust=-0.5 throughout in an attempt to see how the source sizes evolve during the pipeline.

If required I can then try to do simulations for both DR1 and DR2 style observations. Not sure quite what this will show either because the sources need to be injected with the solutions that were already derived from the DR2 and DR1 runs.

**Comment by twshimwell** [comment]
Completed a run with smoothing turned off throughout. Turns out this doesnt seem to impact the source sizes and even with smoothing off the sources are slightly larger than DR1.

In DR1 the uvmin in the calibration did cause slight holes around compact sources. I wonder if this could play a role in making the recovered source sizes slightly less.

**Comment by twshimwell** [comment]
I think this issue is ready for closing as we are not really looking into it anymore. Conclusion was that we couldnt isolate a single step to be responsible for enlarging the source sizes.
