### ISSUE TITLE
Polarisation imaging

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#74]
Create Q and U cubes with 480 channels about 3 degrees across. This is ~7000 pixels with 1.5arcsec cellsize (current high imaging cellsize) or ~2400 pixels with 4.5arcsec cellsize.

Testing so far has shown that ~1000 pixels is fine with the memory constraints but its unclear what the maximum is.

It would be also nice to produce a stokes V image. My thoughts would be that this can be done with the 4.5arcsec cellsize at 20arcsec resolution.

**Comment by twshimwell** [comment]
A full bandwidth low resolution Stokes V image takes about 1hr. There is some structure in V around some sources (attached -- V is left I is right), is this to be expected do you think?

![screenshot 2018-06-27 13 28 15](https://user-images.githubusercontent.com/12065270/41971248-0a85b32c-7a0e-11e8-82da-ef687d59e8b4.png)

We have 2 pulsars in the HETDEX region so ill try those fields and see if we detect either of those.

**Comment by sposullivan** [comment]
Yes the structure in V gives an indication of the instrumental polarisation. Marco Iacobelli mentioned yesterday that he was interested in imaging Stokes V across the HETDEX area to get a handle on the instrumental polarisation variation across the beam. I think he was planning to use wsclean on the prefactor data, so maybe you can chat to him (he's not here the rest of the week I believe).

**Comment by sposullivan** [comment]
Cameron Van Eck doesn't mention imaging Stokes V in his paper but it might be worth checking with him in case they are just sitting on a disk somewhere.

**Comment by twshimwell** [comment]
I can redo them all. Its just an hour per field processing if I just do this step (so no DD). The main time will be downloading and unpacking (especially as SARA is down at the moment).

**Comment by twshimwell** [comment]
OK and for the QU cubes I chatted a little with @sposullivan and given there is no deconvolution in QU the resolved RM structures might be hard to  accurately measure due to sidelobes. So, perhaps for DR2 processing we stick with low resolution imaging of QU.

For the full field of view we need ~2500 pixels but trying this on 256GB ram caused a memory error. 2000 pixels also crashed. 1000 works.

I guess what we will have to do is do 4x1250 pixel images with different phase centers.

I can put this into the pipeline if people are happy with this idea?

**Comment by cyriltasse** [comment]
sounds excelent to me...

**Comment by twshimwell** [comment]
OK ive changed pipeline.py and created do_polcubes.py so that now we should get polarisation images (4 cubes of 480 channels and 1250x1250 pixels distributed to cover ~3x3 deg). An example polarisation cube is on https://www.dropbox.com/s/rpqg7ujli9wdyls/image_full_low_QU_Cube0.cube.dirty.corr.fits?dl=0 if anyone wants to check this looks ok.

**Comment by mhardcastle** [comment]
Made this an option -- not everyone using the pipeline will want it.

**Comment by mhardcastle** [comment]
Tim, wouldn't it be better to make the cubes over the full field but with fewer channels and then stitch them together in frequency? Then if we get QU deconvolution at some point in the future we can deconvolve them properly.

**Comment by twshimwell** [comment]
OK ive pushed a change that now does this 1/4 of the bandwidth at a time. 

I guess we also now need something to glue the cubes together.

**Comment by sposullivan** [comment]
No idea about error messages but if you start at Chan 120 should you have ChanEnd=239, or leave it unset?
-------- Original message --------From: twshimwell <notifications@github.com> Date: 7/3/18  13:26  (GMT+01:00) To: mhardcastle/ddf-pipeline <ddf-pipeline@noreply.github.com> Cc: sposullivan <shaneosullivan.kerry@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [mhardcastle/ddf-pipeline] Polarisation imaging (#74) 
Imaging the 2nd part of the bandwidth I get an error in DDFacet.
Traceback (most recent call last):

File "/home/shimwell/.local/bin/DDF.py", line 6, in 

exec(compile(open(file).read(), file, 'exec'))

File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/DDF.py", line 387, in 

main(OP, messages)

File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/DDF.py", line 228, in main

Imager.Init()

File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Imager/ClassDeconvMachine.py", line 169, in Init

GD=self.GD)

File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassVisServer.py", line 91, in init

self.Init()

File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassVisServer.py", line 137, in Init

first_ms=self.ListMS[0] if self.ListMS else None)

File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassMS.py", line 120, in init

self.ReadMSInfo(first_ms=first_ms,DoPrint=DoPrint)

File "/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassMS.py", line 1040, in ReadMSInfo

self.dFreq = ta_spectral.getcol("CHAN_WIDTH")[self._spwid,self.ChanSlice].flatten()[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

13:25:19 - ClearSHM                  | Clear shared memory
13:25:19 - ClearSHM                  | Clear Semaphores
13:25:19 - ClearSHM                  | Clear shared dictionaries

FAILED to run DDF.py --Output-Name=image_full_low_QU_Cube1 --Data-MS=big-mslist.txt --Deconv-PeakFactor 0.001000 --Data-ColName DATA_DI_CORRECTED --Parallel-NCPU=32 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=0 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.250000 --Image-NPix=2500 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 4.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --GAClean-AllowNegativeInitHMP True --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 20.000000 --Weight-ColName="IMAGING_WEIGHT" --Output-Cubes=dD --RIME-PolMode=QU --Output-Mode=Dirty  --Freq-NBand=120 --Selection-ChanStart=120 --Selection-ChanEnd=240 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=5.00 --DDESolutions-GlobalNorm=None --DDESolutions-DDModeGrid=AP --DDESolutions-DDModeDeGrid=AP --DDESolutions-DDSols=DDS3_full_smoothed --Selection-UVRangeKm=[0.100000,25.750000] --GAClean-MinSizeInit=10 --Beam-Smooth=1: return value is 1

Any ideas?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhardcastle/ddf-pipeline","title":"mhardcastle/ddf-pipeline","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhardcastle/ddf-pipeline"}},"updates":{"snippets":[{"icon":"PERSON","message":"@twshimwell in #74: Imaging the 2nd part of the bandwidth I get an error in DDFacet.\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/shimwell/.local/bin/DDF.py\", line 6, in \u003cmodule\u003e\r\n    exec(compile(open(__file__).read(), __file__, 'exec'))\r\n  File \"/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/DDF.py\", line 387, in \u003cmodule\u003e\r\n    main(OP, messages)\r\n  File \"/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/DDF.py\", line 228, in main\r\n    Imager.Init()\r\n  File \"/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Imager/ClassDeconvMachine.py\", line 169, in Init\r\n    GD=self.GD)\r\n  File \"/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassVisServer.py\", line 91, in __init__\r\n    self.Init()\r\n  File \"/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassVisServer.py\", line 137, in Init\r\n    first_ms=self.ListMS[0] if self.ListMS else None)\r\n  File \"/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassMS.py\", line 120, in __init__\r\n    self.ReadMSInfo(first_ms=first_ms,DoPrint=DoPrint)\r\n  File \"/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Data/ClassMS.py\", line 1040, in ReadMSInfo\r\n    self.dFreq = ta_spectral.getcol(\"CHAN_WIDTH\")[self._spwid,self.ChanSlice].flatten()[0]\r\nIndexError: index 0 is out of bounds for axis 0 with size 0\r\n - 13:25:19 - ClearSHM                  | Clear shared memory\r\n - 13:25:19 - ClearSHM                  | Clear Semaphores\r\n - 13:25:19 - ClearSHM                  | Clear shared dictionaries\r\nFAILED to run DDF.py --Output-Name=image_full_low_QU_Cube1 --Data-MS=big-mslist.txt --Deconv-PeakFactor 0.001000 --Data-ColName DATA_DI_CORRECTED --Parallel-NCPU=32 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=0 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.250000 --Image-NPix=2500 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 4.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --GAClean-AllowNegativeInitHMP True --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 20.000000 --Weight-ColName=\"IMAGING_WEIGHT\" --Output-Cubes=dD --RIME-PolMode=QU --Output-Mode=Dirty  --Freq-NBand=120 --Selection-ChanStart=120 --Selection-ChanEnd=240 --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=5.00 --DDESolutions-GlobalNorm=None --DDESolutions-DDModeGrid=AP --DDESolutions-DDModeDeGrid=AP --DDESolutions-DDSols=DDS3_full_smoothed --Selection-UVRangeKm=[0.100000,25.750000] --GAClean-MinSizeInit=10 --Beam-Smooth=1: return value is 1\r\n\r\nAny ideas?"}],"action":{"name":"View Issue","url":"https://github.com/mhardcastle/ddf-pipeline/issues/74#issuecomment-402119269"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhardcastle/ddf-pipeline/issues/74#issuecomment-402119269",
"url": "https://github.com/mhardcastle/ddf-pipeline/issues/74#issuecomment-402119269",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mhardcastle/ddf-pipeline] Polarisation imaging (#74)",
"sections": [
{
"text": "",
"activityTitle": "**twshimwell**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@twshimwell",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 74,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 74\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mhardcastle/ddf-pipeline/issues/74#issuecomment-402119269"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 350546708\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by cyriltasse** [comment]
These keywords are for the individual MSs...

**Comment by twshimwell** [comment]
Ah yes so it breaks when ChanStart falls outside the first msfile (so from 20 onwards). Is this a DDFacet bug or feature?

**Comment by twshimwell** [comment]
I've pushed changes that add in StokesV imaging as a option. This also uses the low resolution imaging parameters.

**Comment by mhardcastle** [comment]
Why don't you do it N MS at a time, then you don't need any selection at all?

I can write something to cubify it later.

**Comment by cyriltasse** [comment]
That's also what I do to do the shifted restored cubes...

**Comment by mhardcastle** [comment]
So you could copy Cyril's code, even better (-:

**Comment by twshimwell** [comment]
Ok, now one MS at a time. Each low resolution QU cube of 20 chans takes about 10mins.

**Comment by mhardcastle** [comment]
Or 5 mins on a proper computer (-: .

I'll write something to put these together.

**Comment by twshimwell** [comment]
Wonder how long a high res one would take on a proper computer.

**Comment by mhardcastle** [comment]
Guess we should see how much use the low-res ones are and then think again.

Cube-making code added to polcube and pushed.

**Comment by twshimwell** [comment]
Made a stokes-v map with and without the DD corrections to show the difference we are getting. Left without DD and right with DD (so in the pipeline). Certainly cleans it up a lot and the noise is about 0.08mJy/beam. I'm not sure if we would expect DD to also do something to real stokes V sources but maybe that would require some simulations as im not sure we have any real stokes V sources to use for testing.

![screenshot 2018-07-04 10 01 14](https://user-images.githubusercontent.com/12065270/42264600-6fcdb3de-7f71-11e8-9afa-f2c5b92b5b60.png)

**Comment by mhardcastle** [comment]
Do you mean left with, right without?

**Comment by twshimwell** [comment]
Ah yes I did indeed mean that.

**Comment by cyriltasse** [comment]
You've scared me...

**Comment by twshimwell** [comment]
I've put a cube on ftp://ftp.strw.leidenuniv.nl/pub/shimwell/image_full_low_QU.cube.dirty.corr.fits if you want to check it looks ok @sposullivan 

A few changes are still needed to make this work for observations observed multiple times but then this issue is done assuming the cube looks ok.

**Comment by sposullivan** [comment]
Thanks @twshimwell, downloading now. I will check this tomorrow, and report back. 
So neither of the two pulsars have Stokes V?

**Comment by twshimwell** [comment]
No neither yet have obvious excess Stokes V emission but we have only looked in the DI Stokes-V images (DD are not available yet) and we still need to write something that does the Stokes-V source finding and calculates the fractional stokes-V to look at the fractional polarisation. So its not very thorough yet.

**Comment by sposullivan** [comment]
Nice results from a known polarised source in the field (from image_full_low_QU.cube.dirty.corr.fits). 
![screenshot](https://user-images.githubusercontent.com/36737785/42329028-1908c624-8070-11e8-90a6-506bafc64aae.png)
Same RM as from WSClean imaging of prefactor data: 
![screenshot](https://user-images.githubusercontent.com/36737785/42329093-3da3d67c-8070-11e8-9456-f6a2da115b7f.png)
I had to make a sub-cube around this source because I couldn't load entire cube into memory for RM synthesis. I will try again soon on computer with more memory (256 GB). Otherwise will split into smaller cubes for RM synthesis.

**Comment by sposullivan** [comment]
@twshimwell I found 9 (real) polarised sources in total in that cube, so that would imply a source density ~6 times higher than in Van Eck+18. The rms noise in Q and U is ~84 uJy/beam across the centre of the field and increases to ~100 uJy/beam in some of the noisier facets. 
![image](https://user-images.githubusercontent.com/36737785/42439388-16a9510a-8363-11e8-8fde-f8ef4f700ce2.png)
The green circle is 2.5 deg diameter. As you can see, leakage from the brighter sources can still be problematic...
It takes ~2 hours to do the RM synthesis and RMclean (if I use a mask, only including pixels with Stokes I > 1 mJy/beam)

**Comment by cyriltasse** [comment]
Would be ice to cross check if these sources are also seen in adjacent pointings... just to be sure it's not some weird effect. If indeed much higher it's great... 2 hours is really not very much for the pipeline, if you want to run `RMclean` within.

**Comment by mhardcastle** [comment]
If we want to put pyrmsynth in the pipeline then adapting it to be able to read in our cubes should not be too hard.

Is the reason the facets show up in @sposullivan 's images that we don't use a smooth beam for the QU imaging?

**Comment by twshimwell** [comment]
Yeh I was just checking the smooth-beam thing too. Very odd noise structure.

These were run with beam-smooth=1 so im a bit surprised to see the facets like that.

**Comment by twshimwell** [comment]
Similarly the Stokes V images dont seem to have the smooth beam either. The command for the stokes V is. Does smooth-beam work for imaging polarisation?

DDF.py --Output-Name=image_full_low_stokesV --Data-MS=big-mslist.txt --Deconv-PeakFactor 0.001000 --Data-ColName DATA_DI_CORRECTED --Parallel-NCPU=32 --Beam-CenterNorm=1 --Deconv-CycleFactor=0 --Deconv-MaxMinorIter=1000000 --Deconv-MaxMajorIter=0 --Deconv-Mode SSD --Beam-Model=LOFAR --Beam-LOFARBeamMode=A --Weight-Robust -0.250000 --Image-NPix=6000 --CF-wmax 50000 --CF-Nw 100 --Output-Also onNeds --Image-Cell 4.500000 --Facets-NFacets=11 --SSDClean-NEnlargeData 0 --Freq-NDegridBand 1 --Beam-NBand 1 --Facets-DiamMax 1.5 --Facets-DiamMin 0.1 --Deconv-RMSFactor=3.000000 --SSDClean-ConvFFTSwitch 10000 --Data-Sort 1 --Cache-Dir=. --Log-Memory 1 --GAClean-RMSFactorInitHMP 1.000000 --GAClean-MaxMinorIterInitHMP 10000.000000 --GAClean-AllowNegativeInitHMP True --DDESolutions-SolsDir=SOLSDIR --Cache-Weight=reset --Output-Mode=Clean --Output-RestoringBeam 20.000000 --Weight-ColName="IMAGING_WEIGHT" --Freq-NBand=2 --RIME-PolMode=IV --Output-Mode=Dirty --RIME-DecorrMode=FT --SSDClean-SSDSolvePars [S,Alpha] --SSDClean-BICFactor 0 --Mask-Auto=1 --Mask-SigTh=5.00 --DDESolutions-GlobalNorm=None --DDESolutions-DDModeGrid=AP --DDESolutions-DDModeDeGrid=AP --DDESolutions-DDSols=DDS3_full_smoothed --Selection-UVRangeKm=[0.100000,25.750000] --GAClean-MinSizeInit=10 --Beam-Smooth=1

**Comment by twshimwell** [comment]
Hmm weird images when attempting to make very low resolution cubes... not seen this type of behavior before. The bottom right bit of the image is all nans...

<img width="404" alt="screenshot 2018-07-09 15 31 02" src="https://user-images.githubusercontent.com/12065270/42453505-3e18dac4-838d-11e8-93b1-4f834f5d5301.png">

**Comment by cyriltasse** [comment]
I've implemented a mask to remove the interesting science.... Can you redo in I-stokes?

**Comment by twshimwell** [comment]
Remaking in stokes I (by simply changing RIME-PolMode=QU to =I) shows the same science removing mask.

During these runs I see this in the log 

================ Making Dirty Image and/or PSF ====================
/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Imager/ClassFacetMachine.py:719: RuntimeWarning: invalid value encountered in divide
  sw /= np.max(sw)
/net/para10/data1/shimwell/software/killmsddf/new-install/DDFacet/DDFacet/Imager/ClassFacetMachine.py:721: RuntimeWarning: invalid value encountered in less


![screenshot 2018-07-09 17 19 43](https://user-images.githubusercontent.com/12065270/42459635-5cc42c08-839c-11e8-9a1f-4582f5258303.png)

**Comment by twshimwell** [comment]
Looks normal to me
![screenshot 2018-07-09 17 37 40](https://user-images.githubusercontent.com/12065270/42460709-db2cacda-839e-11e8-9387-ea7cecbf5d1d.png)

Ive put an example log on https://www.dropbox.com/s/pkkmpdozaw25t3m/DDF-image_full_vlow_QU_Cube12.log?dl=0

**Comment by cyriltasse** [comment]
`F21_S32` look devil

**Comment by cyriltasse** [comment]
Can you pull again on the DDFacet active branch (`ddf_pipeline_fixes_may18`) and try again? Perhaps remove your *.ddfcache before running

**Comment by cyriltasse** [comment]
Hold on - this might make things bad

**Comment by cyriltasse** [comment]
can you just try to increase `--Facets-DiamMin = 0.2` for example

**Comment by twshimwell** [comment]
Changing that parameter didnt fix it. However, just doubling the image size did so I think its all fine.

**Comment by twshimwell** [comment]
With these polarisation images the main thing left is to get the smooth beam. @cyriltasse did you have any ideas why the beam might not be smooth for these images?

**Comment by twshimwell** [comment]
Ive pushed changes to parset.py, do_polcubes.py and pipeline.py so that we now have very low resolution (uvmax 1.6km) polarisation imaging in the pipeline.

**Comment by sposullivan** [comment]
The RM synthesis products will be larger (depending on sampling in Faraday depth). But at least we would want to cover -150 to +150 rad/m2, and a sampling of 0.15 rad/m2 would be good, which is ~92 GB cube. And we need 3 (p, q and u) cubes. And that is just the dirty cubes, not doing RMclean. 
We could bring up any long-term storage issues at the Krakow MKSP meeting?

**Comment by twshimwell** [comment]
OK that sounds a bit large then... Presently we have the primary beam corrected and uncorrected cubes stored. Can we perhaps just keep the primary beam corrected ones?

**Comment by rvweeren** [comment]
> On 6 Aug 2018, at 12:24, twshimwell <notifications@github.com> wrote:
> 
> OK that sounds a bit large then... Presently we have the primary beam corrected and uncorrected cubes stored. Can we perhaps just keep the primary beam corrected ones?
> 
> 

For polarization it can help to have uncorrected (for the primary beam) cubes. That makes it easier to deal with the Ricean bias in the polarization analysis.

**Comment by mhardcastle** [comment]
Also if we ever want to make mosaics in Q and U we want the beam correction.

**Comment by cyriltasse** [comment]
Why not keep the RM cubes only on islands?

**Comment by sposullivan** [comment]
Maube sensible for field sources, not diffuse. Might effect anyone wanting to do polarization stacking later...
For 1 mJy/beam cut of some pointing I was testing, goes from 5.8e6 pixels to 8e4.

**Comment by cyriltasse** [comment]
But the diffuse stuff is the low-res cube Marta was testing, or some kind or some kind of intermediate scale where you'd need the high res cube?

    Le lundi 6 août 2018 à 17:18:23 UTC+2, sposullivan <notifications@github.com> a écrit :  
 
 
Maube sensible for field sources, not diffuse. Might effect anyone wanting to do polarization stacking later...
For 1 mJy/beam cut of some pointing I was testing, goes from 5.8e6 pixels to 8e4.

**Comment by sposullivan** [comment]
Yes just low-res (4') and high-res (20") cubes at the moment, as far as I know. Little RM cubes around every bright Stokes I source at 20" would be really cool as a pipeline product, linked to a VO catalog table maybe.

**Comment by mhardcastle** [comment]
I think we've decided to live with the large datasets for now or to compress as suggested in #90. So closing this.
