### ISSUE TITLE
pipeline dies if not running a field in the fields table

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/ddf-pipeline#86]
Hangs with

Welcome to ddf-pipeline, version v2.0-12-g7f55359
Running: CleanSHM.py
 - 13:24:03 - ClearSHM                  | Clear shared memory
 - 13:24:03 - ClearSHM                  | Clear Semaphores
 - 13:24:03 - ClearSHM                  | Clear shared dictionaries
Traceback (most recent call last):
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 1461, in <module>
    main(o)
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 752, in main
    update_status(None,'Running',time='start_date')
  File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/surveys_db.py", line 28, in update_status
    idd['status']=status
TypeError: 'NoneType' object does not support item assignment

**Comment by mhardcastle** [comment]
The environment variable enabling database use shouldn't be set in this case. That's what it's for.
-------- Original message --------From: twshimwell <notifications@github.com> Date: 01/08/2018  12:25  (GMT+00:00) To: mhardcastle/ddf-pipeline <ddf-pipeline@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [mhardcastle/ddf-pipeline] pipeline dies if not running a field in
  the fields table (#86) 
Hangs with
Welcome to ddf-pipeline, version v2.0-12-g7f55359

Running: CleanSHM.py

13:24:03 - ClearSHM                  | Clear shared memory
13:24:03 - ClearSHM                  | Clear Semaphores
13:24:03 - ClearSHM                  | Clear shared dictionaries

Traceback (most recent call last):

File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 1461, in 

main(o)

File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/scripts/pipeline.py", line 752, in main

update_status(None,'Running',time='start_date')

File "/net/para10/data1/shimwell/software/killmsddf/ddf-pipeline-DR2/ddf-pipeline/utils/surveys_db.py", line 28, in update_status

idd['status']=status

TypeError: 'NoneType' object does not support item assignment


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhardcastle/ddf-pipeline","title":"mhardcastle/ddf-pipeline","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhardcastle/ddf-pipeline"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"pipeline dies if not running a field in the fields table (#86)"}],"action":{"name":"View Issue","url":"https://github.com/mhardcastle/ddf-pipeline/issues/86"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhardcastle/ddf-pipeline/issues/86",
"url": "https://github.com/mhardcastle/ddf-pipeline/issues/86",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "pipeline dies if not running a field in the fields table (#86)",
"sections": [
{
"text": "",
"activityTitle": "**twshimwell**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@twshimwell",
"facts": [
{
"name": "Repository: ",
"value": "mhardcastle/ddf-pipeline"
},
{
"name": "Issue #: ",
"value": 86
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 86,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mhardcastle/ddf-pipeline\",\n\"issueId\": 86\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mhardcastle/ddf-pipeline/issues/86"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 363416106\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by twshimwell** [comment]
Ah i see, certainly makes sense. Thanks.
